Repository wfrice/TSA-Video-Game, pull requests merged in 2021-12, with the labels that each got.

#11 Backend
  index.js
Labels: backend

#21 Changed Size of some text
  index.js
Labels: level

#25 Stylesheet handling
  config.js
  index.html
  index.js
  kaboom.js
  style.css
Labels: enhancement, backend

#32 General refactoring -> situation-one
  Levels/level1.js
  config.js
  index.html
  index.js
  kaboom.js
  layers.js
  spriteMaker.js
Labels: refactoring
