Repository wfrice/TSA-Video-Game, pull requests merged in 2022-01, with the labels that each got.

#35 Keyboard input
  index.js
  spriteMaker.js
  ui/button.js
  ui/buttonSeries.js
Labels: documentation, enhancement, refactoring, ui

#36 Situation one
  Levels/level1.js
  Tiles/carTileSet.png
  Tiles/mainBackground.png
  config.js
  index.html
  index.js
  kaboom.js
  layers.js
  style.css
  ui/button.js
  ui/buttonSeries.js
Labels: documentation, enhancement, backend, refactoring, ui

#58 Fully functional dialog, baby!
  dialog.js
  index.js
  input.js
  layers.js
  maps/level1.js
  maps/level2.js
  maps/level3.js
  maps/lose.js
  player.js
  ui/button.js
  ui/buttonSeries.js
  ui/dialog.js
  ui/dialogButton.js
  ui/dialogButtonSeries.js
Labels: enhancement, level, refactoring, ui, visuals

#59 Fixed whoopsies
  maps/level1.js
  maps/level2.js
  maps/level3.js
  maps/level4.js
  player.js
  ui/dialog.js
Labels: enhancement, refactoring

#68 Sprite areas
  input.js
  maps/level1.js
  maps/level2.js
  maps/level3.js
  maps/level4.js
  player.js
  spriteLoader.js
  sprites/tiles/BilliardTable.png
  ui/button.js
  ui/dialog.js
Labels: enhancement, refactoring, ui, visuals
